### ISSUE TITLE
API level?

### ISSUE THREAD

**Issue by stevelyall** [binder-app/android#21]
Our current min SDK version is 21, what do you guys think about trying to reduce this somewhat? Right now we're only supporting Lollipop and higher, do we think this could be limit who we can test with somewhat?

Thoughts?

**Comment by mitchhentges** [comment]
This shouldn't be too bad, just need to change a `context.getResources()` in `FirstLaunchActivity` to `ContextCompat.getResources()` (or something).
Then we should be down to API 14 or so
