### ISSUE TITLE
Handle Profile Creation Failure

### ISSUE THREAD

**Issue by stevelyall** [binder-app/android#23]

**Comment by mitchhentges** [comment]
The `ProfileCreationRequest` or whatever should return "false" on profile creation failure

**Comment by stevelyall** [comment]
It currently returns false on failure and the failure handler runs. Shall we just tell the user it failed and let them try again later?

**Comment by mitchhentges** [comment]
I'd say tell the user it failed, but let them try again whenever (e.g. don't enforce "later" delay). It would be nice if we could discriminate between network connection failure and server failure, but that's a problem for a _real_ project
