### ISSUE TITLE
Make Year formatting consistent

### ISSUE THREAD

**Issue by stevelyall** [binder-app/android#27]
The year input in FirstLaunchActivity is a String (`1st`), the Profile object takes an int, the API handles it as a string, and the suggestions view shows it as a concatenated string (`Year 1`). 

To save us some sub-stringing, parsing, concatenating, etc, we should decide on a single way the year should be inputted and displayed. 

My suggestion would be to take it in as a string ex) `1st`, and just reuse this everywhere and concatenate it with `year` when the profile is viewed. 
Any ideas?

**Comment by mitchhentges** [comment]
I think `Year n` is a little more self-explanatory, and then we also don't need to worry about  the "st", "nd", "rd", "th" after each number

**Comment by stevelyall** [comment]
PR #30 fixes this
