### ISSUE TITLE
Store course list on client-side, don't allow users to specify their own

### ISSUE THREAD

**Issue by mitchhentges** [binder-app/android#33]

**Comment by stevelyall** [comment]
#44 adds the list of courses, now how do we want them sorted and displayed in the ProfileCreationActivity?

Filter by subject?
Autocomplete?

@binder-app/owners

**Comment by mitchhentges** [comment]
Do neat-o filtering view thinger that you were talking about.
If you can't _restrict_ users to the list of courses, simply block users from using invalid courses during validation
