### ISSUE TITLE
User Photo and Name should be stored locally after profile creation

### ISSUE THREAD

**Issue by roddicks** [binder-app/android#48]
We need to have access to the user's name and photo while viewing matches.

Perhaps just store the whole Profile object that we create?

**Comment by mitchhentges** [comment]
Is this necessary? Maybe the name, but do we use the photo again, ever? Will we, for Prototype 4?

**Comment by mitchhentges** [comment]
Yes it is: #52.
Use the `SharedPreference` keys `profile_name` and `profile_photo`
